#!/bin/sh

# PROVIDE: streama_server


. /etc/rc.subr

name=streama_server
rcvar=streama_server_enable
pidfile_child="/var/run/${name}.pid"
pidfile="/var/run/${name}_daemon.pid"
logfile="/var/log/${name}.log"
streama_server_chdir="/usr/home/streama"

command="/usr/sbin/daemon"
start_precmd="${name}_prestart"

daemon="java"

load_rc_config $name
: ${streama_server_enable:=no}

streama_server_prestart() {

    # set the daemon / java flags
    rc_flags="-u 'streama' -r -P ${pidfile} -p ${pidfile_child}  /usr/local/bin/java -jar /usr/home/streama/streama-1.7.0-RC13jar >> /usr/home/streama/streama_server.log 2>&1 ${rc_flags}"

    touch $pidfile
}

streama_server_describe() {
    echo "Service for running streama."
}


run_rc_command "$1"